#!/usr/bin/env bash

set -x

# DEBUG
yabai -m config debug_output on

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="15"
gaps["bottom"]="24"
gaps["left"]="15"
gaps["right"]="15"
gaps["inner"]="15"

color["focused"]="0xff775759"
color["normal"]="0x00000000"
color["preselect"]="0xE02d74da"

ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"dotfiles-bar-spaces-jsx\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# ===== Initialization

source ~/.config/yabai/scripts/initialization.sh

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config top_padding                 "${gaps["top"]}"
yabai -m config bottom_padding              "${gaps["bottom"]}"
yabai -m config left_padding                "${gaps["left"]}"
yabai -m config right_padding               "${gaps["right"]}"
yabai -m config window_gap                  "${gaps["inner"]}"


yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               off

yabai -m config window_border               on
yabai -m config window_border_width         3
yabai -m config active_window_border_color  "0xFF00FF000"
yabai -m config normal_window_border_color  "0x00FFFFFFF"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off


# ===== Mouse =================================

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         off
yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Signals ===============================

# Initialize the temp folder when adding or removing displays
yabai -m signal --add event=display_added action="~/.config/yabai/scripts/initialization.sh"
yabai -m signal --add event=display_removed action="~/.config/yabai/scripts/initialization.sh"


# ===== Rules ==================================

# Hack to be able to focus across display where you have stacked windows
yabai -m rule --add app="Hammerspoon" manage=off layer="below"

# Unmanaged Windows
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^Finder$" layer=above manage=off
yabai -m rule --add app="^Microsoft Outlook$" manage=off 
yabai -m rule --add app="^Wally$" sticky=on layer=above manage=off
yabai -m rule --add label="Chrome" app="^Chrome$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add title="^(Preferences)" app="WebStorm" manage=off
set +x
printf "yabai: configuration loaded...\\n"
